kind: Service
apiVersion: v1
metadata:
  name: connections-svc
  namespace: cloud-native-appconfig      
spec:
  selector:
    app: connections
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: connections
  namespace: cloud-native-appconfig      
  labels:
    app: connections
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connections
  template:
    metadata:
      labels:
        app: connections
    spec:
      containers:
      - name: connections
        image: cdavisafc/cloudnative-appconfig-connections:0.0.2
        env:
          - name: INSTANCE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: SPRING_APPLICATION_JSON
            value: '{"spring":{"datasource":{"url":"jdbc:mysql://mysql-svc:3306/cookbook"}}}'
          - name: SPRING_APPLICATION_NAME
            value: "mycookbook"
          - name: SPRING_CLOUD_CONFIG_URI
            value: "http://sccs-svc:8888"
          - name: SPRING_PROFILES_ACTIVE
            value: "dev"            