kind: Service
apiVersion: v1
metadata:
  name: connectionsposts-svc
  namespace: cloud-native-appconfig    
spec:
  selector:
    app: connectionsposts
  ports:
  - protocol: "TCP"
    port: 8082
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: connectionsposts
  namespace: cloud-native-appconfig    
  labels:
    app: connectionsposts
spec:
  replicas: 2
  selector:
    matchLabels:
      app: connectionsposts
  template:
    metadata:
      labels:
        app: connectionsposts
    spec:
      containers:
      - name: connectionsposts
        image: cdavisafc/cloudnative-appconfig-connectionposts:0.0.1
        env:
          - name: INSTANCE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: CONNECTIONPOSTSCONTROLLER_POSTSURL
            value: "http://172.17.0.6:8080/posts?userIds="
          - name: CONNECTIONPOSTSCONTROLLER_CONNECTIONSURL
            value: "http://172.17.0.5:8080/connections/"
          - name: CONNECTIONPOSTSCONTROLLER_USERSURL
            value: "http://172.17.0.5:8080/users/"
          - name: REDIS_HOSTNAME
            value: "172.17.0.2"
          - name: REDIS_PORT
            value: "6379"